# Generated by Django 3.1.7 on 2021-02-25 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210225_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('librarian_perm', 'Set book as returned'),)},
        ),
    ]
