# Generated by Django 3.1.7 on 2021-02-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210225_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('librarian_perm', 'May add/update/delete info'),)},
        ),
    ]
